name: 'Deploy to AppStore & PlayStore'

on:
  workflow_dispatch:
    inputs:
      platform:
        type: 'choice'
        description: 'Platform of release (ios, android, all)'
        required: true
        default: 'all'
        options:
          - ios
          - android
          - all

jobs:
  deploy-ios:
    name: Build and Deploy to App Store
    runs-on: self-hosted
    if: github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all'
    steps:
      - name: 'Cleanup build folder'
        run: |
          echo "Current working directory: "
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          echo "Finish cleanup...new working directory: "
          ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node and npm
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Run Expo Prebuild
        run: npx expo prebuild
        env:
          APP_VARIANT: production
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          USED_CI: 'github' # this is to allow injecting release keystore

      - name: Run fastlane deploy
        run: fastlane ios deploy
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT}}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID}}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID}}

  deploy-android:
    name: Build and Deploy to Play Store
    runs-on: self-hosted
    if: github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all'
    steps:
      - name: 'Cleanup build folder'
        run: |
          echo "Current working directory: "
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          echo "Finish cleanup...new working directory: "
          ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node and npm
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Run Expo Prebuild
        run: npx expo prebuild
        env:
          APP_VARIANT: production
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          USED_CI: 'github' # this is to allow injecting release keystore

      - name: Decode keystore from base64
        env:
          ENCODED_STRING: ${{ secrets.RELEASE_KEY_BASE64 }}
        run: |
          echo $ENCODED_STRING | base64 -d > release.keystore

      - name: Run fastlane android deploy
        run: fastlane android deploy
        env:
          GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY }}
          GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY_ID: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY_ID }}
          GOOGLE_PLAY_SERVICE_ACCOUNT_PROJECT_ID: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_PROJECT_ID }}
          GOOGLE_PLAY_SERVICE_ACCOUNT_CLIENT_ID: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_CLIENT_ID }}
