name: Trigger EAS Update
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'EAS update message'
        required: false
        default: 'Minor enhancements and bug fixes :p'
jobs:
  update:
    name: EAS Update
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node and npm
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install

      - name: Publish update
        run: npx eas-cli update --branch=production --message="${{ github.event.inputs.message }}"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
